export const AMOUNT_OF_TIME_TO_GENERATE_HASE = 3
export const MAX_DISTANCE_IN_KILOMETERS_TO_DO_CHECK_IN = 0.1 // distance in KM
export const PAGINATION_LIMIT = 20
export const LIMIT_IN_MINUTES_TO_VALIDATE_CHECK_IN = 20
